// Sourdough Lab — 数据镜像（仅保留主页 UI 需要的字段）
window.BASE = {
  id: 'sourdough-classic',
  name: '乡村酸种',
  nameLatin: 'Country Sourdough',
  baseFlour: 400,
  hydration: 0.70,
  ingredients: [
    { id: 'flour',   name: 'T65 高筋粉', bp: 1.00, role: 'flour',   isHydration: false },
    { id: 'water',   name: '水',         bp: 0.70, role: 'liquid',  isHydration: true  },
    { id: 'starter', name: '鲁邦种',     bp: 0.20, role: 'leaven',  isHydration: false },
    { id: 'salt',    name: '盐',         bp: 0.02, role: 'salt',    isHydration: false },
  ],
  defaults: { waterReservedRatio: 0.10, feedBufferGrams: 60 },
  breadColor: { h: 38, s: 25, l: 82 },
};

window.MODIFIERS = {
  walnut:           { name:'核桃',          nameLatin:'Walnut',         category:'addin',    dose:0.12,  dotColor:{h:30,s:25,l:30},  stage:'fold-3' },
  olive:            { name:'卡拉马塔橄榄',   nameLatin:'Olive',          category:'addin',    dose:0.10,  dotColor:{h:330,s:25,l:22}, stage:'fold-2' },
  rosemary:         { name:'迷迭香',         nameLatin:'Rosemary',       category:'addin',    dose:0.01,  dotColor:{h:95,s:35,l:30},  stage:'fold-2' },
  fig:              { name:'无花果干',       nameLatin:'Fig',            category:'addin',    dose:0.21,  dotColor:{h:28,s:35,l:35},  stage:'fold-2' },
  cocoa:            { name:'可可粉',         nameLatin:'Cocoa',          category:'colorant', dose:0.04,  breadColor:{h:20,s:40,l:35},stage:'mix', absorb:0.65 },
  'chocolate-chips':{ name:'黑巧克力豆',     nameLatin:'Dark Chocolate', category:'addin',    dose:0.22,  dotColor:{h:18,s:35,l:20},  stage:'fold-3' },
  jalapeno:         { name:'腌墨西哥辣椒',   nameLatin:'Jalapeño',       category:'addin',    dose:0.24,  dotColor:{h:80,s:45,l:40},  stage:'fold-3' },
  cheddar:          { name:'车达奶酪',       nameLatin:'Cheddar',        category:'addin',    dose:0.15,  dotColor:{h:38,s:60,l:55},  stage:'fold-3' },
  cranberry:        { name:'蔓越莓干',       nameLatin:'Cranberry',      category:'addin',    dose:0.16,  dotColor:{h:355,s:55,l:40}, stage:'fold-2', absorb:0.30 },
  'pumpkin-seed':   { name:'南瓜籽',         nameLatin:'Pumpkin Seed',   category:'addin',    dose:0.05,  dotColor:{h:85,s:35,l:32},  stage:'fold-3' },
  'sunflower-seed': { name:'葵花籽',         nameLatin:'Sunflower Seed', category:'addin',    dose:0.05,  dotColor:{h:38,s:35,l:42},  stage:'fold-3' },
  sesame:           { name:'芝麻',           nameLatin:'Sesame',         category:'addin',    dose:0.05,  dotColor:{h:38,s:25,l:55},  stage:'fold-3' },
  pumpkin:          { name:'南瓜粉',         nameLatin:'Pumpkin',        category:'colorant', dose:0.08,  breadColor:{h:28,s:55,l:60},stage:'mix', absorb:0.70 },
  cinnamon:         { name:'肉桂粉',         nameLatin:'Cinnamon',       category:'colorant', dose:0.012, breadColor:{h:24,s:40,l:55},stage:'mix', absorb:0.35 },
  matcha:           { name:'抹茶粉',         nameLatin:'Matcha',         category:'colorant', dose:0.029, breadColor:{h:90,s:30,l:62},stage:'mix', absorb:0.80 },
};

window.FLAVORS = [
  { id:'plain',            name:'原味',         nameLatin:'Country Bread',         modifiers:[],
    source:{name:'Tartine Bread', author:'Chad Robertson'},
    difficulty:'beginner', note:'Robertson 经典 75% 水合配方；新手可从 70% 起步。' },
  { id:'walnut-levain',    name:'核桃乡村',     nameLatin:'Walnut Levain',
    modifiers:[{id:'walnut',dose:0.12}],
    source:{name:'Tartine Bread — Walnut Country', author:'Chad Robertson'},
    difficulty:'intermediate', note:'坚果须烤过冷却；第 2 或第 3 次折叠时加入。' },
  { id:'olive-rosemary',   name:'橄榄迷迭香',   nameLatin:'Olive & Rosemary',
    modifiers:[{id:'olive',dose:0.10},{id:'rosemary',dose:0.01}],
    source:{name:'Tartine Bread — Olive Rosemary', author:'Chad Robertson'},
    difficulty:'intermediate', note:'橄榄带盐，基础盐减 0.2%。' },
  { id:'fig-walnut',       name:'无花果核桃',   nameLatin:'Fig & Walnut',
    modifiers:[{id:'fig',dose:0.21},{id:'walnut',dose:0.24}],
    source:{name:'King Arthur'}, difficulty:'intermediate',
    note:'原方水合 63%；大量干果加水合补偿后约 72%。' },
  { id:'chocolate',        name:'可可巧克力',   nameLatin:'Chocolate Sourdough',
    modifiers:[{id:'cocoa',dose:0.04},{id:'chocolate-chips',dose:0.22}],
    source:{name:'King Arthur'}, difficulty:'intermediate',
    note:'可可先和水拌匀去结块；推荐 Dutch-process 可可。' },
  { id:'jalapeno-cheddar', name:'辣椒车达',     nameLatin:'Jalapeño Cheddar',
    modifiers:[{id:'jalapeno',dose:0.24},{id:'cheddar',dose:0.15}],
    source:{name:'King Arthur'}, difficulty:'intermediate',
    note:'奶酪一半磨碎一半切块；辣椒含盐，基础盐减 0.2%。' },
  { id:'walnut-cranberry', name:'核桃蔓越莓',   nameLatin:'Walnut Cranberry',
    modifiers:[{id:'walnut',dose:0.12},{id:'cranberry',dose:0.16}],
    source:{name:'The Perfect Loaf', author:'Maurizio Leo'},
    difficulty:'intermediate', note:'蔓越莓略泡温水再加入；酸度促发酵，主发酵缩短 10–15%。' },
  { id:'seeded',           name:'混合种子',     nameLatin:'Seeded Sourdough',
    modifiers:[{id:'pumpkin-seed',dose:0.05},{id:'sunflower-seed',dose:0.05},{id:'sesame',dose:0.05}],
    source:{name:'The Perfect Loaf', author:'Maurizio Leo'},
    difficulty:'intermediate', note:'种子烤过香气更浓；最后一次折叠时加入。' },
  { id:'pumpkin-cinnamon', name:'南瓜肉桂',     nameLatin:'Pumpkin Cinnamon',
    modifiers:[{id:'pumpkin',dose:0.08},{id:'cinnamon',dose:0.012}],
    source:{name:'The Perfect Loaf', author:'Maurizio Leo'},
    difficulty:'intermediate', note:'南瓜粉吸水大，水合度会升至约 75%。' },
  { id:'matcha-swirl',     name:'抹茶漩涡',     nameLatin:'Matcha Swirl',
    modifiers:[{id:'matcha',dose:0.029}],
    source:{name:'King Arthur (adapted)'}, difficulty:'advanced',
    note:'原方为奶油吐司；此处为 sourdough 改编版，颜色会因烤制略偏橄榄绿。' },
];

// 流程步骤（简化版）
window.STEPS = [
  { id:'feed',     phase:'prep',  num:'I',    title:'喂种',      latin:'Feed Starter',    minutes:480, temp:26, tip:'1:5:5 比例喂养，室温 24°C 等 6–8h 至峰值' },
  { id:'autolyse', phase:'prep',  num:'II',   title:'水合静置',  latin:'Autolyse',         minutes:45,  tip:'面粉 + 水（不含预留水）静置 45 分钟' },
  { id:'mix',      phase:'bulk',  num:'III',  title:'入盐搅拌',  latin:'Mix',              minutes:15,  tip:'加入鲁邦种 + 盐 + 预留水，rubaud 手法拌匀' },
  { id:'fold-1',   phase:'bulk',  num:'IV',   title:'折叠 × 1',  latin:'Stretch & Fold',   minutes:30 },
  { id:'fold-2',   phase:'bulk',  num:'V',    title:'折叠 × 2',  latin:'Stretch & Fold',   minutes:30 },
  { id:'fold-3',   phase:'bulk',  num:'VI',   title:'折叠 × 3',  latin:'Stretch & Fold',   minutes:30 },
  { id:'rest',     phase:'bulk',  num:'VII',  title:'主发酵完成',latin:'Bulk Rest',        minutes:90 },
  { id:'shape',    phase:'shape', num:'VIII', title:'整形',      latin:'Pre-shape & Shape',minutes:20 },
  { id:'cold',     phase:'cold',  num:'IX',   title:'冷藏发酵',  latin:'Cold Retard',      minutes:960, tip:'4°C 冷藏 12–18h，发展风味' },
  { id:'bake',     phase:'bake',  num:'X',    title:'烘烤',      latin:'Bake',             minutes:45,  temp:250, tip:'铸铁锅 250°C 预热，加盖 20 分钟后开盖' },
];
