/**
 * Add-ins — 混入料（坚果/干果/种子/香草/奶酪/其他）
 *
 * Schema 与 colorant 类似，但：
 *   - category 固定 'addin'
 *   - breadColor 通常为 null（不改整体色，只在 BreadPreview 上作为夹杂点)
 *   - dotColor  在 BreadPreview 上的颗粒/碎末颜色 (HSL or hex)
 *   - preTreatment  'toast' | 'soak' | 'chop' | null
 *   - soakingLiquidRatio  浸泡液相对自重的比例（浸泡类使用）
 */

export const ADDINS = [
  // ───────── 坚果 ─────────
  {
    id: 'walnut',
    name: '核桃',
    nameLatin: 'Walnut',
    category: 'addin',
    dose: { default: 0.12, min: 0.08, max: 0.15 },
    preTreatment: 'toast',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 25, s: 35, l: 30 },
    flavor: ['nutty', 'earthy'],
    worksWith: ['raisin', 'cranberry', 'rosemary'],
    addStage: 'fold-3',
    warnings: ['预烤 2-3 分钟激发风味'],
  },
  {
    id: 'almond',
    name: '杏仁',
    nameLatin: 'Almond',
    category: 'addin',
    dose: { default: 0.10, min: 0.08, max: 0.12 },
    preTreatment: 'toast',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 35, s: 30, l: 55 },
    flavor: ['nutty'],
    worksWith: ['honey', 'orange-zest'],
    addStage: 'fold-3',
    warnings: [],
  },
  {
    id: 'pecan',
    name: '山核桃',
    nameLatin: 'Pecan',
    category: 'addin',
    dose: { default: 0.12, min: 0.08, max: 0.15 },
    preTreatment: 'toast',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 28, s: 40, l: 35 },
    flavor: ['nutty', 'sweet'],
    worksWith: ['maple', 'cinnamon'],
    addStage: 'fold-3',
    warnings: ['可可脂含量高，预烤时间略减'],
  },

  // ───────── 种子 ─────────
  {
    id: 'pumpkin-seed',
    name: '南瓜籽',
    nameLatin: 'Pumpkin Seed',
    category: 'addin',
    dose: { default: 0.08, min: 0.05, max: 0.10 },
    preTreatment: 'soak',
    hydrationAdjust: { method: 'soaking-liquid', ratio: 1.0 },  // 浸泡 12h 等量水
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 85, s: 30, l: 40 },
    flavor: ['nutty', 'mild'],
    worksWith: ['rye', 'sunflower-seed'],
    addStage: 'fold-1',
    warnings: ['浸泡 12 小时，浸液并入总水'],
  },
  {
    id: 'sesame',
    name: '芝麻',
    nameLatin: 'Sesame',
    category: 'addin',
    dose: { default: 0.04, min: 0.03, max: 0.05 },
    preTreatment: 'toast',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 30, s: 30, l: 25 },
    flavor: ['nutty'],
    worksWith: ['black-sesame', 'soy'],
    addStage: 'fold-3',
    warnings: [],
  },
  {
    id: 'poppy-seed',
    name: '罂粟籽',
    nameLatin: 'Poppy Seed',
    category: 'addin',
    dose: { default: 0.03, min: 0.02, max: 0.04 },
    preTreatment: null,
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 230, s: 20, l: 18 },
    flavor: ['nutty', 'crunchy'],
    worksWith: ['lemon', 'almond'],
    addStage: 'fold-3',
    warnings: [],
  },
  {
    id: 'flax-seed',
    name: '亚麻籽',
    nameLatin: 'Flax Seed',
    category: 'addin',
    dose: { default: 0.06, min: 0.05, max: 0.08 },
    preTreatment: 'soak',
    hydrationAdjust: { method: 'soaking-liquid', ratio: 1.0 },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 30, s: 35, l: 30 },
    flavor: ['nutty'],
    worksWith: ['oats', 'whole-wheat'],
    addStage: 'fold-1',
    warnings: ['浸泡产生黏胶，需并入总水'],
  },
  {
    id: 'sunflower-seed',
    name: '向日葵籽',
    nameLatin: 'Sunflower Seed',
    category: 'addin',
    dose: { default: 0.10, min: 0.08, max: 0.12 },
    preTreatment: 'soak',
    hydrationAdjust: { method: 'soaking-liquid', ratio: 1.0 },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 40, s: 35, l: 40 },
    flavor: ['nutty'],
    worksWith: ['pumpkin-seed', 'rye'],
    addStage: 'fold-1',
    warnings: [],
  },

  // ───────── 干果 ─────────
  {
    id: 'cranberry',
    name: '蔓越莓',
    nameLatin: 'Cranberry',
    category: 'addin',
    dose: { default: 0.10, min: 0.08, max: 0.12 },
    preTreatment: 'soak',
    hydrationAdjust: { method: 'soaking-liquid', ratio: 0.6 },
    fermentationAdjust: { delayMinutes: -15, sugarBoostGrams: 0, reason: '糖酸加速发酵' },
    glutenAdjust: null,
    dotColor: { h: 350, s: 65, l: 40 },
    flavor: ['sweet', 'tart'],
    worksWith: ['walnut', 'orange-zest'],
    addStage: 'fold-3',
    warnings: [],
  },
  {
    id: 'raisin',
    name: '葡萄干',
    nameLatin: 'Raisin',
    category: 'addin',
    dose: { default: 0.12, min: 0.10, max: 0.15 },
    preTreatment: 'soak',
    hydrationAdjust: { method: 'soaking-liquid', ratio: 0.5 },
    fermentationAdjust: { delayMinutes: -20, sugarBoostGrams: 0, reason: '高糖显著加速主发酵' },
    glutenAdjust: null,
    dotColor: { h: 20, s: 50, l: 25 },
    flavor: ['sweet'],
    worksWith: ['cinnamon', 'walnut', 'oats'],
    addStage: 'fold-3',
    warnings: ['主发酵缩短 10-20%，密切观察'],
  },
  {
    id: 'sundried-tomato',
    name: '风干番茄',
    nameLatin: 'Sun-Dried Tomato',
    category: 'addin',
    dose: { default: 0.08, min: 0.05, max: 0.10 },
    preTreatment: 'soak',
    hydrationAdjust: { method: 'soaking-liquid', ratio: 0.5 },
    fermentationAdjust: { delayMinutes: -10, sugarBoostGrams: 0, reason: '糖酸轻微加速' },
    glutenAdjust: null,
    dotColor: { h: 10, s: 60, l: 35 },
    flavor: ['savory', 'umami'],
    worksWith: ['basil', 'olive', 'rosemary'],
    addStage: 'fold-3',
    warnings: ['咸度需调节基础盐'],
  },
  {
    id: 'apricot',
    name: '杏干',
    nameLatin: 'Apricot',
    category: 'addin',
    dose: { default: 0.10, min: 0.08, max: 0.12 },
    preTreatment: 'soak',
    hydrationAdjust: { method: 'soaking-liquid', ratio: 0.4 },
    fermentationAdjust: { delayMinutes: -10, sugarBoostGrams: 0, reason: '糖分轻微加速' },
    glutenAdjust: null,
    dotColor: { h: 30, s: 65, l: 55 },
    flavor: ['sweet', 'tart'],
    worksWith: ['almond', 'honey'],
    addStage: 'fold-3',
    warnings: [],
  },

  // ───────── 香草 ─────────
  {
    id: 'rosemary',
    name: '迷迭香',
    nameLatin: 'Rosemary',
    category: 'addin',
    dose: { default: 0.015, min: 0.01, max: 0.02 },
    preTreatment: null,
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: { delayMinutes: 5, sugarBoostGrams: 0, reason: '精油轻微抗菌' },
    glutenAdjust: null,
    dotColor: { h: 90, s: 30, l: 30 },
    flavor: ['herbal', 'piney'],
    worksWith: ['olive-oil', 'garlic', 'walnut'],
    addStage: 'fold-3',
    warnings: [],
  },
  {
    id: 'basil',
    name: '罗勒',
    nameLatin: 'Basil',
    category: 'addin',
    dose: { default: 0.01, min: 0.005, max: 0.015 },
    preTreatment: null,
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 95, s: 40, l: 35 },
    flavor: ['herbal', 'sweet'],
    worksWith: ['sundried-tomato', 'olive-oil'],
    addStage: 'fold-3',
    warnings: [],
  },
  {
    id: 'thyme',
    name: '百里香',
    nameLatin: 'Thyme',
    category: 'addin',
    dose: { default: 0.015, min: 0.01, max: 0.02 },
    preTreatment: null,
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 85, s: 25, l: 30 },
    flavor: ['herbal', 'earthy'],
    worksWith: ['cheese', 'honey'],
    addStage: 'fold-3',
    warnings: [],
  },

  // ───────── 奶酪 ─────────
  {
    id: 'cheddar',
    name: '车达奶酪',
    nameLatin: 'Cheddar',
    category: 'addin',
    dose: { default: 0.08, min: 0.05, max: 0.10 },
    preTreatment: 'chop',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: { delayMinutes: 5, sugarBoostGrams: 0, reason: '脂肪轻微延缓' },
    glutenAdjust: null,
    dotColor: { h: 35, s: 75, l: 55 },
    flavor: ['savory', 'salty', 'umami'],
    worksWith: ['jalapeno', 'garlic', 'chive'],
    addStage: 'fold-3',
    warnings: ['咸度叠加，基础盐酌减 0.5%'],
  },
  {
    id: 'parmesan',
    name: '帕玛森',
    nameLatin: 'Parmesan',
    category: 'addin',
    dose: { default: 0.06, min: 0.03, max: 0.08 },
    preTreatment: 'chop',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 45, s: 35, l: 70 },
    flavor: ['savory', 'umami'],
    worksWith: ['rosemary', 'black-pepper'],
    addStage: 'fold-3',
    warnings: ['咸度叠加'],
  },

  // ───────── 其他 ─────────
  {
    id: 'olive',
    name: '橄榄',
    nameLatin: 'Olive',
    category: 'addin',
    dose: { default: 0.08, min: 0.05, max: 0.10 },
    preTreatment: 'chop',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 70, s: 35, l: 25 },
    flavor: ['savory', 'briny'],
    worksWith: ['rosemary', 'sundried-tomato', 'thyme'],
    addStage: 'fold-3',
    warnings: ['去核切粒，沥干盐水；基础盐酌减 0.5%'],
  },
  {
    id: 'garlic',
    name: '大蒜',
    nameLatin: 'Garlic',
    category: 'addin',
    dose: { default: 0.02, min: 0.01, max: 0.03 },
    preTreatment: null,
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 50, s: 20, l: 80 },
    flavor: ['pungent', 'savory'],
    worksWith: ['rosemary', 'cheddar', 'olive-oil'],
    addStage: 'fold-3',
    warnings: ['用干蒜粉更稳定，新鲜切碎易变黑'],
  },
];

export const ADDINS_BY_ID = Object.fromEntries(
  ADDINS.map((a) => [a.id, a])
);

export function getAddin(id) {
  return ADDINS_BY_ID[id] || null;
}
