/**
 * Add-ins — 混入料（坚果 / 干果 / 种子 / 奶酪 / 辣椒等）
 *
 * 每条引用大师级来源。无权威来源者（罗勒、百里香、大蒜、帕玛森、
 * 杏干、日晒番茄）已剔除。
 *
 * Schema 额外字段：
 *   source  { name, url?, page? }   权威来源
 */

export const ADDINS = [
  // ── 坚果类 ───────────────────────────────────
  {
    id: 'walnut',
    name: '核桃',
    nameLatin: 'Walnut',
    category: 'addin',
    dose: { default: 0.12, min: 0.08, max: 0.24 },
    preTreatment: 'toast',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 30, s: 25, l: 30 },
    flavor: ['nutty', 'earthy'],
    worksWith: ['cranberry', 'fig', 'olive'],
    addStage: 'fold-3',
    warnings: ['烘烤坚果需完全冷却再加入，防止破坏面筋'],
    source: {
      name: 'Tartine Bread — Walnut Country Bread',
      url: 'https://www.amazon.com/Tartine-Bread-Chad-Robertson/dp/0811870413',
    },
  },
  {
    id: 'pecan',
    name: '美洲山核桃',
    nameLatin: 'Pecan',
    category: 'addin',
    dose: { default: 0.10, min: 0.08, max: 0.15 },
    preTreatment: 'toast',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 28, s: 30, l: 38 },
    flavor: ['buttery', 'nutty'],
    worksWith: ['cranberry', 'cinnamon'],
    addStage: 'fold-3',
    warnings: [],
    source: {
      name: 'King Arthur — Cranberry Pecan Sourdough (variation)',
      url: 'https://www.kingarthurbaking.com/recipes',
    },
  },

  // ── 种子类 ───────────────────────────────────
  {
    id: 'pumpkin-seed',
    name: '南瓜籽',
    nameLatin: 'Pumpkin Seed',
    category: 'addin',
    dose: { default: 0.08, min: 0.06, max: 0.12 },
    preTreatment: 'toast',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 85, s: 35, l: 32 },
    flavor: ['nutty', 'roasty'],
    worksWith: ['pumpkin', 'turmeric'],
    addStage: 'fold-3',
    warnings: [],
    source: {
      name: 'The Perfect Loaf — Seeded Sourdough',
      url: 'https://www.theperfectloaf.com/seeded-sourdough/',
    },
  },
  {
    id: 'sunflower-seed',
    name: '葵花籽',
    nameLatin: 'Sunflower Seed',
    category: 'addin',
    dose: { default: 0.08, min: 0.06, max: 0.10 },
    preTreatment: 'toast',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 38, s: 35, l: 42 },
    flavor: ['nutty', 'mild'],
    worksWith: ['turmeric', 'sesame'],
    addStage: 'fold-3',
    warnings: [],
    source: {
      name: 'The Perfect Loaf — Seeded Sourdough',
      url: 'https://www.theperfectloaf.com/seeded-sourdough/',
    },
  },
  {
    id: 'sesame',
    name: '芝麻',
    nameLatin: 'Sesame',
    category: 'addin',
    dose: { default: 0.05, min: 0.03, max: 0.08 },
    preTreatment: null,
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 38, s: 25, l: 55 },
    flavor: ['nutty', 'aromatic'],
    worksWith: ['sunflower-seed', 'pumpkin-seed'],
    addStage: 'fold-3',
    warnings: [],
    source: {
      name: 'The Perfect Loaf — Seeded Sourdough',
      url: 'https://www.theperfectloaf.com/seeded-sourdough/',
    },
  },
  {
    id: 'flax-seed',
    name: '亚麻籽',
    nameLatin: 'Flax Seed',
    category: 'addin',
    dose: { default: 0.04, min: 0.03, max: 0.06 },
    preTreatment: 'soak',
    hydrationAdjust: { method: 'soaking-liquid', ratio: 1.0 },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 30, s: 40, l: 30 },
    flavor: ['nutty', 'mild'],
    worksWith: ['sesame', 'sunflower-seed'],
    addStage: 'mix',
    warnings: ['亚麻籽需等重量水浸泡 12h 形成凝胶；浸泡液并入总水'],
    source: {
      name: 'The Perfect Loaf — Seeded Sourdough',
      url: 'https://www.theperfectloaf.com/seeded-sourdough/',
    },
  },

  // ── 干果类 ───────────────────────────────────
  {
    id: 'fig',
    name: '无花果干',
    nameLatin: 'Dried Fig',
    category: 'addin',
    dose: { default: 0.21, min: 0.15, max: 0.25 },
    preTreatment: 'soak-optional',
    hydrationAdjust: { method: 'absorption', ratio: 0.25 },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 28, s: 35, l: 35 },
    flavor: ['sweet', 'earthy'],
    worksWith: ['walnut', 'goat-cheese'],
    addStage: 'fold-2',
    warnings: ['过干时轻泡温水 10 分钟再切粒'],
    source: {
      name: 'King Arthur — Fig & Walnut Sourdough',
      url: 'https://www.kingarthurbaking.com/recipes/fig-and-walnut-sourdough-recipe',
    },
  },
  {
    id: 'cranberry',
    name: '蔓越莓干',
    nameLatin: 'Dried Cranberry',
    category: 'addin',
    dose: { default: 0.16, min: 0.10, max: 0.20 },
    preTreatment: 'soak-optional',
    hydrationAdjust: { method: 'absorption', ratio: 0.30 },
    fermentationAdjust: {
      delayMinutes: -10,
      reason: '糖酸略促发酵',
    },
    glutenAdjust: null,
    dotColor: { h: 355, s: 55, l: 40 },
    flavor: ['tart-sweet'],
    worksWith: ['walnut', 'pecan', 'cocoa'],
    addStage: 'fold-2',
    warnings: [],
    source: {
      name: 'The Perfect Loaf — Walnut Cranberry Sourdough',
      url: 'https://www.theperfectloaf.com/walnut-cranberry-sourdough/',
    },
  },
  {
    id: 'raisin',
    name: '葡萄干',
    nameLatin: 'Raisin',
    category: 'addin',
    dose: { default: 0.21, min: 0.15, max: 0.25 },
    preTreatment: 'soak',
    hydrationAdjust: { method: 'absorption', ratio: 0.35 },
    fermentationAdjust: {
      delayMinutes: -20,
      reason: '高糖加速发酵，主发酵缩短',
    },
    glutenAdjust: null,
    dotColor: { h: 30, s: 40, l: 25 },
    flavor: ['sweet'],
    worksWith: ['cinnamon', 'walnut'],
    addStage: 'fold-2',
    warnings: ['浸泡 2h 后沥干再加入；注意主发酵缩短 10–20%'],
    source: {
      name: 'King Arthur — Sourdough Cinnamon Raisin',
      url: 'https://www.kingarthurbaking.com/recipes/sourdough-cinnamon-raisin-bread-recipe',
    },
  },

  // ── 奶酪 & 咸味 ─────────────────────────────
  {
    id: 'cheddar',
    name: '车达奶酪',
    nameLatin: 'Cheddar',
    category: 'addin',
    dose: { default: 0.15, min: 0.10, max: 0.20 },
    preTreatment: 'dice',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 38, s: 60, l: 55 },
    flavor: ['savory', 'tangy'],
    worksWith: ['jalapeno', 'rosemary'],
    addStage: 'fold-3',
    warnings: ['一半磨碎 + 一半切块效果最佳（融化层 + 保留块状）'],
    source: {
      name: 'King Arthur — Jalapeño-Cheddar Bread',
      url: 'https://www.kingarthurbaking.com/recipes/jalapeno-cheddar-bread-recipe',
    },
  },
  {
    id: 'jalapeno',
    name: '腌墨西哥辣椒',
    nameLatin: 'Pickled Jalapeño',
    category: 'addin',
    dose: { default: 0.24, min: 0.15, max: 0.30 },
    preTreatment: 'drain-chop',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 80, s: 45, l: 40 },
    flavor: ['spicy', 'tangy'],
    worksWith: ['cheddar'],
    addStage: 'fold-3',
    warnings: ['沥干后切碎；带汁会稀释面团'],
    source: {
      name: 'King Arthur — Jalapeño-Cheddar Bread',
      url: 'https://www.kingarthurbaking.com/recipes/jalapeno-cheddar-bread-recipe',
    },
  },
  {
    id: 'olive',
    name: '卡拉马塔橄榄',
    nameLatin: 'Kalamata Olive',
    category: 'addin',
    dose: { default: 0.10, min: 0.08, max: 0.15 },
    preTreatment: 'pit-drain',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 330, s: 25, l: 22 },
    flavor: ['briny', 'umami'],
    worksWith: ['rosemary', 'walnut'],
    addStage: 'fold-2',
    warnings: ['橄榄本身含盐，基础盐可减至 1.8%'],
    source: {
      name: 'Tartine Bread — Olive Country Bread',
      url: 'https://www.amazon.com/Tartine-Bread-Chad-Robertson/dp/0811870413',
    },
  },
  {
    id: 'rosemary',
    name: '迷迭香',
    nameLatin: 'Rosemary',
    category: 'addin',
    dose: { default: 0.01, min: 0.005, max: 0.015 },
    preTreatment: 'chop',
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 95, s: 35, l: 30 },
    flavor: ['herbal', 'piney'],
    worksWith: ['olive', 'cheddar'],
    addStage: 'fold-2',
    warnings: [],
    source: {
      name: 'Tartine Bread — Olive & Rosemary variation',
      url: 'https://www.amazon.com/Tartine-Bread-Chad-Robertson/dp/0811870413',
    },
  },

  // ── 特殊：巧克力豆 ──────────────────────────
  {
    id: 'chocolate-chips',
    name: '黑巧克力豆',
    nameLatin: 'Dark Chocolate Chips',
    category: 'addin',
    dose: { default: 0.22, min: 0.15, max: 0.28 },
    preTreatment: null,
    hydrationAdjust: { method: 'none' },
    fermentationAdjust: null,
    glutenAdjust: null,
    dotColor: { h: 18, s: 35, l: 20 },
    flavor: ['sweet', 'chocolate'],
    worksWith: ['cocoa', 'cherry', 'cranberry'],
    addStage: 'fold-3',
    warnings: ['推荐 60–70% 可可固形物的苦甜巧克力'],
    source: {
      name: 'King Arthur — Chocolate Sourdough',
      url: 'https://www.kingarthurbaking.com/recipes/chocolate-sourdough-bread-recipe',
    },
  },
];

export const ADDINS_BY_ID = Object.fromEntries(
  ADDINS.map((a) => [a.id, a])
);

export function getAddin(id) {
  return ADDINS_BY_ID[id] || null;
}
